### ISSUE TITLE
Safety when clusters or child processes are used

### ISSUE THREAD

**Issue by khalilTN** [abrkn/semaphore.js#15]
Hi,
I'm asking about using semaphore when clusters or maybe child processes are used.
I think, in this case, access will be controlled by cluster, or by childProcess instance, and then 
mutual exclusion will be violated.
Can you clarify ?
Thanks a lot !

**Comment by addaleax** [comment]
@khalilTN Not entirely sure what you are getting at. This module provides a semaphore implementation on the JS level that is not tied to thread- or process-level concurrency, and in particular no child process will “see” the objects from this module.

If you want something like file-system locking, this module is probably not the right thing for you.

If you want to share a semaphore with child processes, you probably need to implement something yourself on top of Node’s IPC (`process.send` & co), but that’s possible to do using this module.

**Comment by khalilTN** [comment]
Thanks for clarifying !

**Comment by addaleax** [comment]
@khalilTN Does this answer your questions fully? :)

**Comment by khalilTN** [comment]
Absolutely ! what i concluded that if i want mutual exclusion to be cross process (cluster), i should not rely on this library.
