### ISSUE TITLE
TypeError: task is not a function

### ISSUE THREAD

**Issue by canard000** [abrkn/semaphore.js#20]
Hello,

I get this error when I use the semaphore as describe in the readme with one token. Do you have an idea on the issue ? Even if I got this error, the code's still running. I hope the semaphor still works 

Best regards,

**Comment by addaleax** [comment]
Can you share a reproduction of the issue?

**Comment by canard000** [comment]
Sorry, it was my fault. I declare explicitly a function into the sem.take() and the issue disappears. You did a good job :)
